/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui;

/**
 *
 * @author andre
 */
public class JFrameAnalytics extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public JFrameAnalytics() {
        initComponents();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTotalCompras = new javax.swing.JLabel();
        jTextFieldTotalCompras = new javax.swing.JTextField();
        jLabelPrecioMaximoCompras = new javax.swing.JLabel();
        jTextFieldPrecioMaxCompras = new javax.swing.JTextField();
        jLabelPrecioMinimoCompras = new javax.swing.JLabel();
        jTextFieldPrecioMinCompras = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTotalCompras1 = new javax.swing.JLabel();
        jLabelTotalServicios = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelTotalTransporte = new javax.swing.JLabel();
        jTextFieldTotalServicios = new javax.swing.JTextField();
        jLabelPrecioMaximoServicios = new javax.swing.JLabel();
        jTextFieldPrecioMaxServicios = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelPrecioMaximoServicios1 = new javax.swing.JLabel();
        jTextFieldPrecioMinServicios = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabelTotalServicios1 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jLabelTotalCompras3 = new javax.swing.JLabel();
        jTextFieldTotalTransporte = new javax.swing.JTextField();
        jLabelPrecioMaximoTransporte = new javax.swing.JLabel();
        jTextFieldPrecioMaxTransporte = new javax.swing.JTextField();
        jTextFieldPrecioMinTransporte = new javax.swing.JTextField();
        jLabelPrecioMinTransporte = new javax.swing.JLabel();
        jLabelPromedioCompras = new javax.swing.JLabel();
        jTextFieldpromedioCompras = new javax.swing.JTextField();
        jLabelPromedioServicios = new javax.swing.JLabel();
        jTextFieldpromedioServicios = new javax.swing.JTextField();
        jLabelPromedioTransporte = new javax.swing.JLabel();
        jTextFieldpromedioTransporte = new javax.swing.JTextField();

        jLabelTitulo1.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("ANALYTICS");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ANALYTICS");
        jDesktopPane1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 6, -1, 50));

        jLabelTotalCompras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotalCompras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalCompras.setText("Gasto Total : $");
        jDesktopPane1.add(jLabelTotalCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 50));

        jTextFieldTotalCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldTotalCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalComprasActionPerformed(evt);
            }
        });
        jTextFieldTotalCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalComprasKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldTotalCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, 30));

        jLabelPrecioMaximoCompras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoCompras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoCompras.setText("Gasto Máximo: $");
        jDesktopPane1.add(jLabelPrecioMaximoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 50));

        jTextFieldPrecioMaxCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMaxCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxComprasActionPerformed(evt);
            }
        });
        jTextFieldPrecioMaxCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMaxComprasKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMaxCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 30));

        jLabelPrecioMinimoCompras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMinimoCompras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMinimoCompras.setText("Gasto Mínimo: $");
        jDesktopPane1.add(jLabelPrecioMinimoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 40));

        jTextFieldPrecioMinCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMinCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinComprasActionPerformed(evt);
            }
        });
        jTextFieldPrecioMinCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMinComprasKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMinCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 30));
        jDesktopPane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 570, 10));

        jLabelTotalCompras1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelTotalCompras1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalCompras1.setText("COMPRAS");
        jDesktopPane1.add(jLabelTotalCompras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 50));

        jLabelTotalServicios.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelTotalServicios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalServicios.setText("SERVICIOS");
        jDesktopPane1.add(jLabelTotalServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 140, 40));
        jDesktopPane1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 52, 270, 0));
        jDesktopPane1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 30));
        jDesktopPane1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, -1));
        jDesktopPane1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 402, 220, 0));

        jLabelTotalTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotalTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalTransporte.setText("Gasto Total: $");
        jDesktopPane1.add(jLabelTotalTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 740, -1, 50));

        jTextFieldTotalServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldTotalServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalServiciosActionPerformed(evt);
            }
        });
        jTextFieldTotalServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldTotalServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 150, 30));

        jLabelPrecioMaximoServicios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoServicios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoServicios.setText("Gasto Máximo: $");
        jDesktopPane1.add(jLabelPrecioMaximoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, 50));

        jTextFieldPrecioMaxServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMaxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxServiciosActionPerformed(evt);
            }
        });
        jTextFieldPrecioMaxServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMaxServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMaxServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 150, 30));
        jDesktopPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 92, 240, 0));
        jDesktopPane1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 10));
        jDesktopPane1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 362, 270, 0));

        jLabelPrecioMaximoServicios1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoServicios1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoServicios1.setText("Gasto Mínimo: $");
        jDesktopPane1.add(jLabelPrecioMaximoServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, 50));

        jTextFieldPrecioMinServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMinServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinServiciosActionPerformed(evt);
            }
        });
        jTextFieldPrecioMinServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMinServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMinServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 150, 30));
        jDesktopPane1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 230, 10));
        jDesktopPane1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 402, 180, 0));
        jDesktopPane1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 2, -1, 20));
        jDesktopPane1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 440, -1));
        jDesktopPane1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));
        jDesktopPane1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, 0));
        jDesktopPane1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 220, 10));
        jDesktopPane1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 580, 10));
        jDesktopPane1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 240, 10));

        jLabelTotalServicios1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelTotalServicios1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalServicios1.setText("TRANSPORTE");
        jDesktopPane1.add(jLabelTotalServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 160, 50));
        jDesktopPane1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 652, 200, 0));
        jDesktopPane1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 652, 200, 0));
        jDesktopPane1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 240, 20));

        jLabelTotalCompras3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotalCompras3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalCompras3.setText("GastoTotal: $");
        jDesktopPane1.add(jLabelTotalCompras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, 50));

        jTextFieldTotalTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldTotalTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTransporteActionPerformed(evt);
            }
        });
        jTextFieldTotalTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldTotalTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, 150, 30));

        jLabelPrecioMaximoTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoTransporte.setText("Gasto Máximo: $");
        jDesktopPane1.add(jLabelPrecioMaximoTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 840, -1, 50));

        jTextFieldPrecioMaxTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMaxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxTransporteActionPerformed(evt);
            }
        });
        jTextFieldPrecioMaxTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMaxTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMaxTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 850, 150, 30));

        jTextFieldPrecioMinTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMinTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinTransporteActionPerformed(evt);
            }
        });
        jTextFieldPrecioMinTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMinTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMinTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 900, 150, 30));

        jLabelPrecioMinTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMinTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMinTransporte.setText("Gasto Mínimo: $");
        jDesktopPane1.add(jLabelPrecioMinTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 890, -1, 50));

        jLabelPromedioCompras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPromedioCompras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedioCompras.setText("Gasto Promedio : $");
        jDesktopPane1.add(jLabelPromedioCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 50));

        jTextFieldpromedioCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldpromedioCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpromedioComprasActionPerformed(evt);
            }
        });
        jTextFieldpromedioCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldpromedioComprasKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldpromedioCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, 30));

        jLabelPromedioServicios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPromedioServicios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedioServicios.setText("Gasto Promedio : $");
        jDesktopPane1.add(jLabelPromedioServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, 50));

        jTextFieldpromedioServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldpromedioServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpromedioServiciosActionPerformed(evt);
            }
        });
        jTextFieldpromedioServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldpromedioServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldpromedioServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 150, 30));

        jLabelPromedioTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPromedioTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedioTransporte.setText("Gasto Promedio : $");
        jDesktopPane1.add(jLabelPromedioTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, -1, 50));

        jTextFieldpromedioTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldpromedioTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpromedioTransporteActionPerformed(evt);
            }
        });
        jTextFieldpromedioTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldpromedioTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldpromedioTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 800, 150, 30));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalComprasActionPerformed

    }//GEN-LAST:event_jTextFieldTotalComprasActionPerformed

    private void jTextFieldTotalComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalComprasKeyTyped

    }//GEN-LAST:event_jTextFieldTotalComprasKeyTyped

    private void jTextFieldPrecioMaxComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxComprasActionPerformed

    private void jTextFieldPrecioMaxComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxComprasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxComprasKeyTyped

    private void jTextFieldPrecioMinComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinComprasActionPerformed

    private void jTextFieldPrecioMinComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinComprasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinComprasKeyTyped

    private void jTextFieldTotalServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalServiciosActionPerformed

    private void jTextFieldTotalServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalServiciosKeyTyped

    private void jTextFieldPrecioMaxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxServiciosActionPerformed

    private void jTextFieldPrecioMaxServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxServiciosKeyTyped

    private void jTextFieldPrecioMinServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinServiciosActionPerformed

    private void jTextFieldPrecioMinServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinServiciosKeyTyped

    private void jTextFieldTotalTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTransporteActionPerformed

    private void jTextFieldTotalTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTransporteKeyTyped

    private void jTextFieldPrecioMaxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxTransporteActionPerformed

    private void jTextFieldPrecioMaxTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxTransporteKeyTyped

    private void jTextFieldPrecioMinTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinTransporteActionPerformed

    private void jTextFieldPrecioMinTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinTransporteKeyTyped

    private void jTextFieldpromedioComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpromedioComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioComprasActionPerformed

    private void jTextFieldpromedioComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldpromedioComprasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioComprasKeyTyped

    private void jTextFieldpromedioServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpromedioServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioServiciosActionPerformed

    private void jTextFieldpromedioServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldpromedioServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioServiciosKeyTyped

    private void jTextFieldpromedioTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpromedioTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioTransporteActionPerformed

    private void jTextFieldpromedioTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldpromedioTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpromedioTransporteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAnalytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelPrecioMaximoCompras;
    private javax.swing.JLabel jLabelPrecioMaximoServicios;
    private javax.swing.JLabel jLabelPrecioMaximoServicios1;
    private javax.swing.JLabel jLabelPrecioMaximoTransporte;
    private javax.swing.JLabel jLabelPrecioMinTransporte;
    private javax.swing.JLabel jLabelPrecioMinimoCompras;
    private javax.swing.JLabel jLabelPromedioCompras;
    private javax.swing.JLabel jLabelPromedioServicios;
    private javax.swing.JLabel jLabelPromedioTransporte;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTotalCompras;
    private javax.swing.JLabel jLabelTotalCompras1;
    private javax.swing.JLabel jLabelTotalCompras3;
    private javax.swing.JLabel jLabelTotalServicios;
    private javax.swing.JLabel jLabelTotalServicios1;
    private javax.swing.JLabel jLabelTotalTransporte;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public static javax.swing.JTextField jTextFieldPrecioMaxCompras;
    public static javax.swing.JTextField jTextFieldPrecioMaxServicios;
    public static javax.swing.JTextField jTextFieldPrecioMaxTransporte;
    public static javax.swing.JTextField jTextFieldPrecioMinCompras;
    public static javax.swing.JTextField jTextFieldPrecioMinServicios;
    public static javax.swing.JTextField jTextFieldPrecioMinTransporte;
    public static javax.swing.JTextField jTextFieldTotalCompras;
    public static javax.swing.JTextField jTextFieldTotalServicios;
    public static javax.swing.JTextField jTextFieldTotalTransporte;
    public static javax.swing.JTextField jTextFieldpromedioCompras;
    public static javax.swing.JTextField jTextFieldpromedioServicios;
    public static javax.swing.JTextField jTextFieldpromedioTransporte;
    // End of variables declaration//GEN-END:variables
}
